package ca.polymtl.inf2990.composants;

import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

import ca.polymtl.inf2990.cpp.FacadeCpp;
import ca.polymtl.inf2990.modele.ProprietesJeu;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FenetreProprietes.java
 *
 * Created on 2014-02-25, 15:14:15
 */
/**
 * 
 * @author mapoug
 */
@SuppressWarnings("serial")
public class FenetreProprietes extends javax.swing.JFrame {

	
	public FenetreProprietes() {
		initComponents();
		ProprietesJeu o = FacadeCpp.fctC_obtenirProprietesJeu();
		jtConditionVictoire.setText(String.valueOf(o.getVictoire()));
		jtFrequenceAsteroide.setText(String.valueOf(o.getFrequence()));
		jtAccelerationBonus.setText(String.valueOf(o.getAcceleration()));
		jtDifficulte.setText(String.valueOf(o.getDifficulte()));
	};

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();
		jtConditionVictoire = new javax.swing.JTextField();
		jtFrequenceAsteroide = new javax.swing.JTextField();
		jtAccelerationBonus = new javax.swing.JTextField();
		jtDifficulte = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		buttonSave = new javax.swing.JButton();
		buttonCancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setText("Propriété de la carte");
		jLabel1.setName("jLabel1"); // NOI18N

		jLabel2.setName("jLabel2"); // NOI18N

		jLabel3.setText("condition de victoire:");
		jLabel3.setName("jLabel3"); // NOI18N

		jLabel4.setText("frequence des astéroides:");
		jLabel4.setName("jLabel4"); // NOI18N

		jLabel5.setText("difficulté:");
		jLabel5.setName("jLabel5"); // NOI18N

		jLabel6.setText("bonus d'accélération:");
		jLabel6.setName("jLabel6"); // NOI18N

		jtConditionVictoire.setName("jTextField1"); // NOI18N

		jtFrequenceAsteroide.setName("jTextField2"); // NOI18N

		jtAccelerationBonus.setName("jTextField3"); // NOI18N
		
		jtDifficulte.setName("jTextField4");
		jtAccelerationBonus
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jTextField3ActionPerformed(evt);
					}
				});

		

		jLabel7.setText("stations restantes");
		jLabel7.setName("jLabel7"); // NOI18N

		jLabel8.setText("astéroides par minute");
		jLabel8.setName("jLabel8"); // NOI18N

		jLabel9.setText("m/(s*s)");
		jLabel9.setName("jLabel9"); // NOI18N

		buttonSave.setText("Save");
		buttonSave.setName("jButton1"); // NOI18N
		buttonSave.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
				
			}
		});

		buttonCancel.setText("Cancel");
		buttonCancel.setName("jButton2"); // NOI18N
		buttonCancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup().addGap(133, 133, 133)
								.addComponent(jLabel1)
								.addContainerGap(246, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel4)
																				.addComponent(
																						jLabel3)
																				.addComponent(
																						jLabel5)
																				.addComponent(
																						jLabel6))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jtAccelerationBonus,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						77,
																						Short.MAX_VALUE)
																				.addComponent(
																						jtConditionVictoire,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						77,
																						Short.MAX_VALUE)
																				.addComponent(
																						jtFrequenceAsteroide,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						77,
																						Short.MAX_VALUE)
																				.addComponent(
																						jtDifficulte,
																						javax.swing.GroupLayout.Alignment.TRAILING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						77,
																						Short.MAX_VALUE))
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED))
												.addGroup(
														javax.swing.GroupLayout.Alignment.TRAILING,
														layout.createSequentialGroup()
																.addComponent(
																		buttonSave,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		130,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(25, 25,
																		25)))
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		69,
																		Short.MAX_VALUE)
																.addComponent(
																		jLabel2)
																.addGap(184,
																		184,
																		184))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(18, 18,
																		18)
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				false)
																				.addComponent(
																						buttonCancel,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel8,
																						javax.swing.GroupLayout.Alignment.LEADING,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						javax.swing.GroupLayout.DEFAULT_SIZE,
																						Short.MAX_VALUE)
																				.addComponent(
																						jLabel7,
																						javax.swing.GroupLayout.Alignment.LEADING)
																				.addComponent(
																						jLabel9,
																						javax.swing.GroupLayout.Alignment.LEADING))
																.addGap(102,
																		102,
																		102)))));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1)
								.addGap(18, 18, 18)
								.addComponent(jLabel2)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(jLabel7)
												.addComponent(
														jtConditionVictoire,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(jLabel8)
												.addComponent(
														jtFrequenceAsteroide,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel6)
												.addComponent(jLabel9)
												.addComponent(
														jtAccelerationBonus,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addComponent(jLabel5)
												.addComponent(
														jtDifficulte,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(34, 34, 34)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(
														buttonCancel,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														52,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														buttonSave,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														54,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));

		pack();
	}// </editor-fold>

	private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		this.dispose();
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		int nbStationSpatiale = 0;
		int frequenceAsteroide = 0;
		int accelerationBonus = 0;
		int difficulte=0;
		try {
			nbStationSpatiale = Integer.parseInt(this.jtConditionVictoire
					.getText());
			frequenceAsteroide = Integer.parseInt(this.jtFrequenceAsteroide
					.getText());
			accelerationBonus = Integer.parseInt(this.jtAccelerationBonus
					.getText());
			difficulte = Integer.parseInt(this.jtDifficulte
					.getText());
			
		} catch (NumberFormatException e) {
			JOptionPane.showMessageDialog(this, "Valeur invalide", "Erreur",
					JOptionPane.ERROR_MESSAGE);
			return;
		}
		if (nbStationSpatiale > 10 || frequenceAsteroide > 120
				|| accelerationBonus > 100 || difficulte>10) {
			JOptionPane.showMessageDialog(this, "Valeur trop élevé", "Erreur",
					JOptionPane.ERROR_MESSAGE);
			;
		}
		if (nbStationSpatiale < 1 || frequenceAsteroide < 20
				|| accelerationBonus <= 0 || difficulte<1) {
			JOptionPane.showMessageDialog(this, "Valeur trop faible", "Erreur",
					JOptionPane.ERROR_MESSAGE);
			;
		}

		else {
			ProprietesJeu pj = new ProprietesJeu(nbStationSpatiale, frequenceAsteroide, accelerationBonus, difficulte);
			FacadeCpp.fctC_modifierProprietesJeu(pj);
			this.dispose();
		}
	}

	/**
	 * @param args
	 *            the command line arguments
	 */

	// Variables declaration - do not modify
	private javax.swing.JButton buttonSave;
	private javax.swing.JButton buttonCancel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JTextField jtConditionVictoire;
	private javax.swing.JTextField jtFrequenceAsteroide;
	private javax.swing.JTextField jtAccelerationBonus;
	private javax.swing.JTextField jtDifficulte;
	
	// End of variables declaration
}
