/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_polymtl_inf2990_cpp_FacadeCpp */

#ifndef _Included_ca_polymtl_inf2990_cpp_FacadeCpp
#define _Included_ca_polymtl_inf2990_cpp_FacadeCpp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_initialiserOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1initialiserOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_libererOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1libererOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_dessinerOpenGL
 * Signature: (Ljava/awt/Canvas;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1dessinerOpenGL
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_redimensionnerFenetre
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1redimensionnerFenetre
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_animer
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1animer
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_zoomIn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1zoomIn
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_zoomOut
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1zoomOut
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    obtenirAffichagesParSeconde
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_obtenirAffichagesParSeconde
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirEtatActionId
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirEtatActionId
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_executerTests
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1executerTests
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_mouseMoved
 * Signature: (IIZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1mouseMoved
  (JNIEnv *, jclass, jint, jint, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_mousePressed
 * Signature: (IIIZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1mousePressed
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_mouseClicked
 * Signature: (IIIZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1mouseClicked
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_mouseDragged
 * Signature: (IIIIZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1mouseDragged
  (JNIEnv *, jclass, jint, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_mouseReleased
 * Signature: (IIIZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1mouseReleased
  (JNIEnv *, jclass, jint, jint, jint, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    keyPressed
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_keyPressed
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    keyReleased
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_keyReleased
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_buttonPressed
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1buttonPressed
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirEtat
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirEtat
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_changerEtat
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1changerEtat
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_ouvrirFichier
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1ouvrirFichier
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_sauvegarderFichier
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1sauvegarderFichier
  (JNIEnv *, jclass, jstring);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_fichierSauvegardeEstDefini
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1fichierSauvegardeEstDefini
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirNomFichierSauvegarde
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirNomFichierSauvegarde
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirSeulNoeudSelectionne
 * Signature: ()Lca/polymtl/inf2990/modele/ProprietesNoeud;
 */
JNIEXPORT jobject JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirSeulNoeudSelectionne
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirProprietesJeu
 * Signature: ()Lca/polymtl/inf2990/modele/ProprietesJeu;
 */
JNIEXPORT jobject JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirProprietesJeu
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_modifierSeulNoeudSelectionne
 * Signature: (Lca/polymtl/inf2990/modele/ProprietesNoeud;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1modifierSeulNoeudSelectionne
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_modifierProprietesJeu
 * Signature: (Lca/polymtl/inf2990/modele/ProprietesJeu;)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1modifierProprietesJeu
  (JNIEnv *, jclass, jobject);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_move
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1move
  (JNIEnv *, jclass, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_getIsGagne
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1getIsGagne
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_isTermine
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1isTermine
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirOptionDebogage
 * Signature: (ZZZZZZZZ)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirOptionDebogage
  (JNIEnv *, jclass, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean, jboolean);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirControles
 * Signature: (IIIIIIIIII)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirControles
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jint, jint, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_obtenirInfoPartie
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1obtenirInfoPartie
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_activerVuePerspective
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1activerVuePerspective
  (JNIEnv *, jclass);

/*
 * Class:     ca_polymtl_inf2990_cpp_FacadeCpp
 * Method:    fctC_activerVueOrthogonale
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_polymtl_inf2990_cpp_FacadeCpp_fctC_1activerVueOrthogonale
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class ca_polymtl_inf2990_cpp_FacadeCpp_EtatModele */

#ifndef _Included_ca_polymtl_inf2990_cpp_FacadeCpp_EtatModele
#define _Included_ca_polymtl_inf2990_cpp_FacadeCpp_EtatModele
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
