/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * test1.java
 *
 * Created on 2014-03-20, 21:13:40
 */
package ca.polymtl.inf2990.configuration;

import java.io.File;
import java.io.IOException;
import java.util.Observable;
import java.util.Observer;

import javax.swing.JOptionPane;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerConfigurationException;
import javax.xml.transform.TransformerException;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;

import org.w3c.dom.Node;

import ca.polymtl.inf2990.composants.Fenetre;
import ca.polymtl.inf2990.cpp.FacadeCpp;

@SuppressWarnings({ "serial", "unused" })
public class test1 extends javax.swing.JFrame implements Observer {
	private configuration config;
	private boutonsControle bouttons;
	private Fenetre fenetrePrincipale;

	@Override
	public void update(Observable o, Object arg) {
		bouttons.setLabel(m_ButtonHautJoueur1,
				String.valueOf(config.gettouches()[0]));
		bouttons.setLabel(m_ButtonGaucheJoueur1,
				String.valueOf(config.gettouches()[1]));
		bouttons.setLabel(m_ButtonDemiTourJoueur1,
				String.valueOf(config.gettouches()[2]));
		bouttons.setLabel(m_ButtonDroiteJoueur1,
				String.valueOf(config.gettouches()[3]));
		bouttons.setLabel(m_ButtonTirJoueur1,
				String.valueOf(config.gettouches()[4]));
		bouttons.setLabel(m_ButtonHautJoueur2,
				String.valueOf(config.gettouches()[5]));
		bouttons.setLabel(m_ButtonDemiTourJoueur2,
				String.valueOf(config.gettouches()[6]));
		bouttons.setLabel(m_ButtonDroiteJoueur2,
				String.valueOf(config.gettouches()[7]));
		bouttons.setLabel(m_ButtonGaucheJoueur2,
				String.valueOf(config.gettouches()[8]));
		bouttons.setLabel(m_ButtonTirJoueur2,
				String.valueOf(config.gettouches()[9]));
	}

	/** Creates new form test1 */
	public test1(Fenetre fenetrePrincipale) {
		this.setResizable(false);
		this.fenetrePrincipale= fenetrePrincipale;
		config = new configuration();
		config.addObserver(this);
		bouttons = new boutonsControle();
		this.setVisible(true);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	public configuration saveConfiguration() {
		config.setmDebug(affichageDeboguageTrue.isSelected());
		config.setaAsteroid(m_RadioButtonAparaitionAsteroide.isSelected());
		config.setchangMode(m_RadioButtonChangementModeVirtuel.isSelected());
		config.seteclairage(m_RadioButtonActiveEclairage.isSelected());
		config.setidentCible(m_RadioButtonIdentificationCible.isSelected());
		config.setcDepart(m_RadioButtonIdentificationCadreDepart.isSelected());
		config.setzPass(m_RadioButtonIdentificationZonePassage.isSelected());
		config.setaPortails(m_RadioButtenIdentificationLimiteAttraction
				.isSelected());
		switch (m_ComboBoxDureePartie.getSelectedIndex()) {
		case 0:
			config.setDureePartie(30);
			break;
		case 1:
			config.setDureePartie(45);
			break;
		case 2:
			config.setDureePartie(60);
			break;
		case 3:
			config.setDureePartie(90);
			break;
		case 4:
			config.setDureePartie(120);
			break;
		case 5:
			config.setDureePartie(150);
			break;
		case 6:
			config.setDureePartie(180);
			break;
		case 7:
			config.setDureePartie(240);
			break;
		case 8:
			config.setDureePartie(300);

			break;
		default:
			break;
		}
		config.setnbVieSspatiales((Integer) m_SpinnerPtVie.getValue());

		return config;
	}

	@SuppressWarnings({ "unchecked", "rawtypes" })
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void LireConfigurationDebogage() {
		try {
			String strCanonicalPath = new File(".").getCanonicalPath();
			String strConfigPath = strCanonicalPath
					+ "\\données\\configuration.xml";
			String strConfigPathDefault = strCanonicalPath
					+ "\\données\\default.xml";
			File f = new File(strConfigPathDefault);
			File fXmlFile = new File(strConfigPath);
			if (!fXmlFile.exists()) {
				fXmlFile = f;
			}

			DocumentBuilderFactory dbFactory = DocumentBuilderFactory
					.newInstance();
			DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
			org.w3c.dom.Document doc = dBuilder.parse(fXmlFile);
			doc.getDocumentElement().normalize();

			Node debug = doc.getElementsByTagName("Debug").item(0);
			Node touche = doc.getElementsByTagName("Touche").item(0);
			Node partie = doc.getElementsByTagName("Partie").item(0);

			boolean bDeboguage, bAparaitionAsteroide, bChangementModeVirtuel, bActiveEclairage, bIdentificationCible, bIdentificationCadreDepart, bIdentificationZonePassage, bIdentificationLimiteAttraction;
			bDeboguage = Boolean.parseBoolean(debug.getAttributes()
					.getNamedItem("affichage_debug").getNodeValue());
			bAparaitionAsteroide = Boolean.parseBoolean(debug.getAttributes()
					.getNamedItem("asteroide").getNodeValue());
			bChangementModeVirtuel = Boolean.parseBoolean(debug.getAttributes()
					.getNamedItem("changement_mode_joueur_virtuel")
					.getNodeValue());
			bActiveEclairage = Boolean.parseBoolean(debug.getAttributes()
					.getNamedItem("eclairage").getNodeValue());
			bIdentificationCible = Boolean.parseBoolean(debug.getAttributes()
					.getNamedItem("identification_cible").getNodeValue());
			bIdentificationCadreDepart = Boolean.parseBoolean(debug
					.getAttributes().getNamedItem("identification_zone_depart")
					.getNodeValue());
			bIdentificationZonePassage = Boolean
					.parseBoolean(debug.getAttributes()
							.getNamedItem("identification_zone_passage")
							.getNodeValue());
			bIdentificationLimiteAttraction = Boolean.parseBoolean(debug
					.getAttributes().getNamedItem("identification_limite")
					.getNodeValue());

			if (bDeboguage) {
				affichageDeboguageTrue.setSelected(bDeboguage);
			} else {
				affichageDeboguageFalse.setSelected(!bDeboguage);
			}

			if (bAparaitionAsteroide) {
				m_RadioButtonAparaitionAsteroide
						.setSelected(bAparaitionAsteroide);
			} else {
				m_RadioButtonAparaitionAsteroideIgnore
						.setSelected(!bAparaitionAsteroide);
			}

			if (bChangementModeVirtuel) {
				m_RadioButtonChangementModeVirtuel
						.setSelected(bChangementModeVirtuel);
			} else {
				m_RadioButtonChangementModeJoueurVirtuelIgnore
						.setSelected(!bChangementModeVirtuel);
			}

			if (bActiveEclairage) {
				m_RadioButtonActiveEclairage.setSelected(bActiveEclairage);
			} else {
				m_RadioButtonActiveEclairageIgnore
						.setSelected(!bActiveEclairage);
			}

			if (bIdentificationCible) {
				m_RadioButtonIdentificationCible
						.setSelected(bIdentificationCible);
			} else {
				m_RadioButtonIdentificationCibleIgnore
						.setSelected(!bIdentificationCible);
			}

			if (bIdentificationCadreDepart) {
				m_RadioButtonIdentificationCadreDepart
						.setSelected(bIdentificationCadreDepart);
			} else {
				m_RadioButtonIdentificationCadreDepartIgnore
						.setSelected(!bIdentificationCadreDepart);
			}

			if (bIdentificationZonePassage) {
				m_RadioButtonIdentificationZonePassage
						.setSelected(bIdentificationZonePassage);
			} else {
				m_RadioButtonIdentificationZonePassageIgnore
						.setSelected(!bIdentificationZonePassage);
			}

			if (bIdentificationLimiteAttraction) {
				m_RadioButtenIdentificationLimiteAttraction
						.setSelected(bIdentificationLimiteAttraction);
			} else {
				m_RadioButtenIdentificationLimiteAttractionIgnore
						.setSelected(!bIdentificationLimiteAttraction);
			}

			String avancer_j1, demitour_j1, droite_j1, gauche_j1, tir_j1, default_j1;
			String avancer_j2, demitour_j2, droite_j2, gauche_j2, tir_j2, default_j2;

			avancer_j1 = touche.getAttributes().getNamedItem("avancer_j1")
					.getNodeValue();
			demitour_j1 = touche.getAttributes().getNamedItem("demitour_j1")
					.getNodeValue();
			droite_j1 = touche.getAttributes().getNamedItem("gauche_j1")
					.getNodeValue();
			gauche_j1 = touche.getAttributes().getNamedItem("gauche_j1")
					.getNodeValue();
			tir_j1 = touche.getAttributes().getNamedItem("tir_j1")
					.getNodeValue();
			default_j1 = touche.getAttributes().getNamedItem("default_j1")
					.getNodeValue();

			avancer_j2 = touche.getAttributes().getNamedItem("avancer_j2")
					.getNodeValue();
			demitour_j2 = touche.getAttributes().getNamedItem("demitour_j2")
					.getNodeValue();
			droite_j2 = touche.getAttributes().getNamedItem("droite_j2")
					.getNodeValue();
			gauche_j2 = touche.getAttributes().getNamedItem("gauche_j2")
					.getNodeValue();
			tir_j2 = touche.getAttributes().getNamedItem("tir_j2")
					.getNodeValue();
			default_j2 = touche.getAttributes().getNamedItem("default_j2")
					.getNodeValue();

			m_ButtonHautJoueur1.setText(avancer_j1);
			m_ButtonDemiTourJoueur1.setText(demitour_j1);
			m_ButtonDroiteJoueur1.setText(droite_j1);
			m_ButtonGaucheJoueur1.setText(gauche_j1);
			m_ButtonTirJoueur1.setText(tir_j1);
			m_ButtonValeurDefautJoueur1.setText(default_j1);

			m_ButtonHautJoueur2.setText(avancer_j2);
			m_ButtonDemiTourJoueur2.setText(demitour_j2);
			m_ButtonDroiteJoueur2.setText(droite_j2);
			m_ButtonGaucheJoueur2.setText(gauche_j2);
			m_ButtonTirJoueur2.setText(tir_j2);
			m_ButtonValeurDefautJoueur2.setText(default_j2);

			int ptVie, duree;
			ptVie = Integer.parseInt(partie.getAttributes()
					.getNamedItem("ptvie").getNodeValue());
			duree = Integer.parseInt(partie.getAttributes()
					.getNamedItem("duree").getNodeValue());

			m_SpinnerPtVie.setValue(ptVie);
			switch (duree) {
			case 30:
				m_ComboBoxDureePartie.setSelectedIndex(0);
				break;
			case 45:
				m_ComboBoxDureePartie.setSelectedIndex(1);
				break;
			case 60:
				m_ComboBoxDureePartie.setSelectedIndex(2);
				break;
			case 90:
				m_ComboBoxDureePartie.setSelectedIndex(3);
				break;
			case 120:
				m_ComboBoxDureePartie.setSelectedIndex(4);
				break;
			case 150:
				m_ComboBoxDureePartie.setSelectedIndex(5);
				break;
			case 180:
				m_ComboBoxDureePartie.setSelectedIndex(6);
				break;
			case 240:
				m_ComboBoxDureePartie.setSelectedIndex(7);
				break;
			case 300:
				m_ComboBoxDureePartie.setSelectedIndex(8);
				break;
			default:
				m_ComboBoxDureePartie.setSelectedIndex(0);
				break;
			}

		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	private void SauverConfigurationDebogage() {
		try {
			DocumentBuilderFactory docFactory = DocumentBuilderFactory
					.newInstance();
			DocumentBuilder docBuilder = docFactory.newDocumentBuilder();

			// root elements
			org.w3c.dom.Document doc = docBuilder.newDocument();
			org.w3c.dom.Element rootElement = doc.createElement("Config");
			doc.appendChild(rootElement);

			org.w3c.dom.Element debug = doc.createElement("Debug");
			debug.setAttribute("affichage_debug",
					String.valueOf(affichageDeboguageTrue.isSelected()));
			debug.setAttribute("asteroide", String
					.valueOf(m_RadioButtonAparaitionAsteroide.isSelected()));
			debug.setAttribute("changement_mode_joueur_virtuel", String
					.valueOf(m_RadioButtonChangementModeVirtuel.isSelected()));
			debug.setAttribute("eclairage",
					String.valueOf(m_RadioButtonActiveEclairage.isSelected()));
			debug.setAttribute("identification_cible", String
					.valueOf(m_RadioButtonIdentificationCible.isSelected()));
			debug.setAttribute("identification_zone_depart", String
					.valueOf(m_RadioButtonIdentificationCadreDepart
							.isSelected()));
			debug.setAttribute("identification_zone_passage", String
					.valueOf(m_RadioButtonIdentificationZonePassage
							.isSelected()));
			debug.setAttribute("identification_limite", String
					.valueOf(m_RadioButtenIdentificationLimiteAttraction
							.isSelected()));
			rootElement.appendChild(debug);

			org.w3c.dom.Element touche = doc.createElement("Touche");
			touche.setAttribute("avancer_j1", m_ButtonHautJoueur1.getText());
			touche.setAttribute("demitour_j1",
					m_ButtonDemiTourJoueur1.getText());
			touche.setAttribute("droite_j1", m_ButtonDroiteJoueur1.getText());
			touche.setAttribute("gauche_j1", m_ButtonGaucheJoueur1.getText());
			touche.setAttribute("tir_j1", m_ButtonTirJoueur1.getText());
			touche.setAttribute("avancer_j2", m_ButtonHautJoueur2.getText());
			touche.setAttribute("demitour_j2",
					m_ButtonDemiTourJoueur2.getText());
			touche.setAttribute("droite_j2", m_ButtonDroiteJoueur2.getText());
			touche.setAttribute("gauche_j2", m_ButtonGaucheJoueur2.getText());
			touche.setAttribute("tir_j2", m_ButtonTirJoueur2.getText());
			touche.setAttribute("default_j1",
					m_ButtonValeurDefautJoueur1.getText());
			touche.setAttribute("default_j2",
					m_ButtonValeurDefautJoueur2.getText());
			rootElement.appendChild(touche);

			org.w3c.dom.Element partie = doc.createElement("Partie");
			int duree;
			switch (m_ComboBoxDureePartie.getSelectedIndex()) {
			case 0:
				duree = 30;
				break;
			case 1:
				duree = 45;
				break;
			case 2:
				duree = 60;
				break;
			case 3:
				duree = 90;
				break;
			case 4:
				duree = 120;
				break;
			case 5:
				duree = 150;
				break;
			case 6:
				duree = 180;
				break;
			case 7:
				duree = 240;
				break;
			case 8:
				duree = 300;
				break;
			default:
				duree = 30;
				break;
			}
			partie.setAttribute("duree", String.valueOf(duree));
			partie.setAttribute("ptvie",
					String.valueOf((Integer) m_SpinnerPtVie.getValue()));
			rootElement.appendChild(partie);

			// write the content into xml file
			TransformerFactory transformerFactory = TransformerFactory
					.newInstance();
			Transformer transformer = null;
			try {
				transformer = transformerFactory.newTransformer();
			} catch (TransformerConfigurationException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
			DOMSource source = new DOMSource(doc);
			String strCanonicalPath;
			try {
				strCanonicalPath = new File(".").getCanonicalPath();
				String strConfigPath = strCanonicalPath
						+ "\\données\\configuration.xml";
				StreamResult result = new StreamResult(new File(strConfigPath));
				try {
					transformer.transform(source, result);
				} catch (TransformerException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} catch (IOException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
		} catch (ParserConfigurationException pce) {
			pce.printStackTrace();
		}
	}

	private void initComponents() {

		// Fenêtre contrôles
		// Joueur 1
		m_ButtonHautJoueur1 = new javax.swing.JButton();
		m_ButtonDemiTourJoueur1 = new javax.swing.JButton();
		m_ButtonDroiteJoueur1 = new javax.swing.JButton();
		m_ButtonGaucheJoueur1 = new javax.swing.JButton();
		m_ButtonTirJoueur1 = new javax.swing.JButton();
		m_ButtonValeurDefautJoueur1 = new javax.swing.JButton();

		// Joueur 2
		m_ButtonHautJoueur2 = new javax.swing.JButton();
		m_ButtonDemiTourJoueur2 = new javax.swing.JButton();
		m_ButtonDroiteJoueur2 = new javax.swing.JButton();
		m_ButtonGaucheJoueur2 = new javax.swing.JButton();
		m_ButtonTirJoueur2 = new javax.swing.JButton();
		m_ButtonValeurDefautJoueur2 = new javax.swing.JButton();

		// Label
		m_LabelJoueur1 = new javax.swing.JLabel("Joueur 1");
		m_LabelAvancer = new javax.swing.JLabel("Avancer");
		m_LabelDemiTour = new javax.swing.JLabel("Demi tour");
		m_LabelTournerDroite = new javax.swing.JLabel("Tourner a  droite");
		m_LabelTournerGauche = new javax.swing.JLabel("Tourner a  gauche");
		m_LabelTir = new javax.swing.JLabel("Tir");
		m_LabelJoueur2 = new javax.swing.JLabel("Joueur 2");

		// Label débogage
		m_LabelApparitionAsteroide = new javax.swing.JLabel(
				"Apparition d'un asteroide");
		m_LabelChangementJoueur = new javax.swing.JLabel(
				"Changement de mode du joueur virtuel");
		m_LabelEclairage = new javax.swing.JLabel(
				"Activation ou desactivation d'un eclairage");
		m_LabelIdentificationJoueur = new javax.swing.JLabel(
				"Identification de la cible du joueur virtuel");
		m_LabelIdentificationCadre = new javax.swing.JLabel(
				"Identification du cadre de depart");
		m_LabelIdentificationZonePassage = new javax.swing.JLabel(
				"Identification de la zone de passage");
		m_LabelIdentificationLimiteAttraction = new javax.swing.JLabel(
				"Identification de la limite d'attraction des portails");
		m_LabelDureePartie = new javax.swing.JLabel("Durée de la partie");
		m_LabelPtVieStations = new javax.swing.JLabel(
				"Points de vie des stations spatialse");
		m_LabelIgnorer = new javax.swing.JLabel("Ignorer");
		m_LabelAfficher = new javax.swing.JLabel("Afficher");
		m_LabelAfficahgeDebogage = new javax.swing.JLabel(
				"Permettre l'affichage des messages de debogages");

		m_ButtonHautJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton15ActionPerformed(evt);
					}
				});

		m_ButtonDemiTourJoueur1
				.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonDemiTourJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton2ActionPerformed(evt);
					}
				});

		m_ButtonDroiteJoueur1.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonDroiteJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton3ActionPerformed(evt);
					}
				});

		m_ButtonGaucheJoueur1.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonGaucheJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton4ActionPerformed(evt);
					}
				});

		m_ButtonTirJoueur1.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonTirJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton5ActionPerformed(evt);
					}
				});

		m_ButtonHautJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton1ActionPerformed(evt);
					}
				});

		m_ButtonDemiTourJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton16ActionPerformed(evt);
					}
				});

		m_ButtonDroiteJoueur2.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonDroiteJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton8ActionPerformed(evt);
					}
				});

		m_ButtonGaucheJoueur2.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonGaucheJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton9ActionPerformed(evt);
					}
				});

		m_ButtonTirJoueur2.setPreferredSize(new java.awt.Dimension(43, 25));
		m_ButtonTirJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton10ActionPerformed(evt);
					}
				});

		m_ButtonValeurDefautJoueur1
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton13ActionPerformed(evt);
					}
				});

		m_ButtonValeurDefautJoueur2
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
						jButton14ActionPerformed(evt);
					}
				});

		jPanel2 = new javax.swing.JPanel();
		m_TabbedPaneTouche = new javax.swing.JTabbedPane();
		jPanel3 = new javax.swing.JPanel();

		filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(1, 30),
				new java.awt.Dimension(1, 30), new java.awt.Dimension(1, 30));

		m_ComboBoxDureePartie = new javax.swing.JComboBox();
		m_SpinnerPtVie = new javax.swing.JSpinner();
		jPanel4 = new javax.swing.JPanel();

		// Radio Button (TRUE)
		affichageDeboguageTrue = new javax.swing.JRadioButton();
		m_RadioButtonAparaitionAsteroide = new javax.swing.JRadioButton();
		m_RadioButtonChangementModeVirtuel = new javax.swing.JRadioButton();
		m_RadioButtonActiveEclairage = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationCible = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationCadreDepart = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationZonePassage = new javax.swing.JRadioButton();
		m_RadioButtenIdentificationLimiteAttraction = new javax.swing.JRadioButton();

		// Radio Button (FALSE)
		affichageDeboguageFalse = new javax.swing.JRadioButton();
		m_RadioButtonAparaitionAsteroideIgnore = new javax.swing.JRadioButton();
		m_RadioButtonChangementModeJoueurVirtuelIgnore = new javax.swing.JRadioButton();
		m_RadioButtonActiveEclairageIgnore = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationCibleIgnore = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationCadreDepartIgnore = new javax.swing.JRadioButton();
		m_RadioButtonIdentificationZonePassageIgnore = new javax.swing.JRadioButton();
		m_RadioButtenIdentificationLimiteAttractionIgnore = new javax.swing.JRadioButton();

		jButton11 = new javax.swing.JButton();
		jButton12 = new javax.swing.JButton();

		m_TabbedPaneTouche.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		m_TabbedPaneTouche.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

		filler2.setBorder(javax.swing.BorderFactory
				.createLineBorder(new java.awt.Color(0, 0, 0)));
		filler2.setOpaque(true);

		buttonGroup1 = new javax.swing.ButtonGroup();
		buttonGroup2 = new javax.swing.ButtonGroup();
		buttonGroup3 = new javax.swing.ButtonGroup();
		buttonGroup4 = new javax.swing.ButtonGroup();
		buttonGroup5 = new javax.swing.ButtonGroup();
		buttonGroup6 = new javax.swing.ButtonGroup();
		buttonGroup7 = new javax.swing.ButtonGroup();
		buttonGroup8 = new javax.swing.ButtonGroup();

		m_ComboBoxDureePartie.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "30 secondes", "45 secondes", "1 minute",
						"1min30", "2min", "2min30", "3min", "4min", "5min" }));

		m_SpinnerPtVie
				.setModel(new javax.swing.SpinnerNumberModel(10, 1, 99, 1));

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(56,
																												56,
																												56)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																m_LabelAvancer)
																														.addComponent(
																																m_LabelDemiTour)
																														.addComponent(
																																m_LabelTournerDroite)
																														.addComponent(
																																m_LabelTournerGauche)
																														.addComponent(
																																m_LabelTir))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addContainerGap(
																												63,
																												Short.MAX_VALUE)
																										.addComponent(
																												m_LabelJoueur1)
																										.addGap(49,
																												49,
																												49)))
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								m_ButtonTirJoueur1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								139,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonGaucheJoueur1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								139,
																								Short.MAX_VALUE)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel3Layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												m_ButtonDemiTourJoueur1,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												139,
																												Short.MAX_VALUE))
																						.addComponent(
																								m_ButtonDroiteJoueur1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								139,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonHautJoueur1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								139,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonValeurDefautJoueur1,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(68,
																				68,
																				68)
																		.addComponent(
																				m_LabelDureePartie)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				m_ComboBoxDureePartie,
																				0,
																				111,
																				Short.MAX_VALUE)))
										.addGap(56, 56, 56)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(12,
																												12,
																												12)
																										.addComponent(
																												m_LabelJoueur2))
																						.addComponent(
																								filler2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(22,
																				22,
																				22)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addComponent(
																								m_ButtonTirJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonGaucheJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonDroiteJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonDemiTourJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonHautJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE)
																						.addComponent(
																								m_ButtonValeurDefautJoueur2,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								147,
																								Short.MAX_VALUE)))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addComponent(
																				m_LabelPtVieStations)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				m_SpinnerPtVie,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				52,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(96, 96, 96)));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(43,
																												43,
																												43)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_LabelAvancer)
																														.addComponent(
																																m_ButtonHautJoueur1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																45,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_ButtonValeurDefautJoueur1)
																														.addComponent(
																																m_LabelJoueur1)
																														.addComponent(
																																m_LabelJoueur2)
																														.addComponent(
																																m_ButtonValeurDefautJoueur2))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												m_ButtonHautJoueur2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												45,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(13,
																				13,
																				13)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_LabelDemiTour)
																														.addComponent(
																																m_ButtonDemiTourJoueur1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																43,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addGap(18,
																												18,
																												18)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_ButtonDroiteJoueur1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																44,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																m_LabelTournerDroite)))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												m_ButtonDemiTourJoueur2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												45,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												m_ButtonDroiteJoueur2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												48,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(10,
																												10,
																												10)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_LabelTournerGauche)
																														.addComponent(
																																m_ButtonGaucheJoueur1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																39,
																																javax.swing.GroupLayout.PREFERRED_SIZE))
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																m_ButtonTirJoueur1,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																40,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																m_LabelTir)))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGap(7,
																												7,
																												7)
																										.addComponent(
																												m_ButtonGaucheJoueur2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												46,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												m_ButtonTirJoueur2,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												46,
																												javax.swing.GroupLayout.PREFERRED_SIZE))))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(40,
																				40,
																				40)
																		.addComponent(
																				filler2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				269,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGap(36, 36, 36)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																m_LabelDureePartie)
														.addComponent(
																m_LabelPtVieStations)
														.addComponent(
																m_ComboBoxDureePartie,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																m_SpinnerPtVie,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																34,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(37, Short.MAX_VALUE)));

		m_TabbedPaneTouche.addTab("Touches", jPanel3);

		/**/
		buttonGroup1.add(affichageDeboguageTrue);
		affichageDeboguageTrue.setText("Oui");
		affichageDeboguageTrue
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup1.add(affichageDeboguageFalse);
		affichageDeboguageFalse.setText("Non");
		/**/

		/**/
		buttonGroup2.add(m_RadioButtonAparaitionAsteroide);
		m_RadioButtonAparaitionAsteroide
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup2.add(m_RadioButtonAparaitionAsteroideIgnore);
		/**/

		/**/
		buttonGroup3.add(m_RadioButtonChangementModeVirtuel);
		m_RadioButtonChangementModeVirtuel
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup3.add(m_RadioButtonChangementModeJoueurVirtuelIgnore);
		/**/

		/**/
		buttonGroup4.add(m_RadioButtonActiveEclairage);
		m_RadioButtonActiveEclairage
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup4.add(m_RadioButtonActiveEclairageIgnore);
		/**/

		/**/
		buttonGroup5.add(m_RadioButtonIdentificationCible);
		m_RadioButtonIdentificationCible
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup5.add(m_RadioButtonIdentificationCibleIgnore);
		/**/

		/**/
		buttonGroup6.add(m_RadioButtonIdentificationCadreDepart);
		m_RadioButtonIdentificationCadreDepart
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup6.add(m_RadioButtonIdentificationCadreDepartIgnore);
		/**/

		/**/
		buttonGroup7.add(m_RadioButtonIdentificationZonePassage);
		m_RadioButtonIdentificationZonePassage
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup7.add(m_RadioButtonIdentificationZonePassageIgnore);
		/**/

		/**/
		buttonGroup8.add(m_RadioButtenIdentificationLimiteAttraction);
		m_RadioButtenIdentificationLimiteAttraction
				.addActionListener(new java.awt.event.ActionListener() {
					public void actionPerformed(java.awt.event.ActionEvent evt) {
					}
				});

		buttonGroup8.add(m_RadioButtenIdentificationLimiteAttractionIgnore);
		/**/

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(85, 85, 85)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																m_LabelIdentificationCadre)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				m_LabelIdentificationJoueur)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								m_LabelChangementJoueur)
																						.addComponent(
																								m_LabelEclairage)
																						.addComponent(
																								m_LabelApparitionAsteroide)))
														.addComponent(
																m_LabelIdentificationLimiteAttraction)
														.addComponent(
																m_LabelIdentificationZonePassage))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												40, Short.MAX_VALUE)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				m_RadioButtonIdentificationCadreDepart)
																		.addGap(30,
																				30,
																				30)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								m_RadioButtenIdentificationLimiteAttractionIgnore)
																						.addComponent(
																								m_RadioButtonIdentificationZonePassageIgnore)
																						.addComponent(
																								m_RadioButtonIdentificationCadreDepartIgnore)
																						.addComponent(
																								m_RadioButtonIdentificationCibleIgnore)
																						.addComponent(
																								m_RadioButtonActiveEclairageIgnore)
																						.addComponent(
																								m_RadioButtonChangementModeJoueurVirtuelIgnore)
																						.addComponent(
																								m_RadioButtonAparaitionAsteroideIgnore)))
														.addComponent(
																m_RadioButtenIdentificationLimiteAttraction)
														.addComponent(
																m_RadioButtonIdentificationZonePassage)
														.addComponent(
																m_RadioButtonIdentificationCible)
														.addComponent(
																m_RadioButtonActiveEclairage)
														.addComponent(
																m_RadioButtonChangementModeVirtuel)
														.addComponent(
																m_RadioButtonAparaitionAsteroide))
										.addGap(235, 235, 235))
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel4Layout.createSequentialGroup()
										.addContainerGap(399, Short.MAX_VALUE)
										.addComponent(m_LabelAfficher)
										.addGap(18, 18, 18)
										.addComponent(m_LabelIgnorer)
										.addGap(219, 219, 219))
						.addGroup(
								jPanel4Layout.createSequentialGroup()
										.addGap(53, 53, 53)
										.addComponent(m_LabelAfficahgeDebogage)
										.addGap(81, 81, 81)
										.addComponent(affichageDeboguageTrue)
										.addGap(35, 35, 35)
										.addComponent(affichageDeboguageFalse)
										.addContainerGap(167, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGap(61, 61, 61)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																m_LabelAfficahgeDebogage)
														.addComponent(
																affichageDeboguageTrue)
														.addComponent(
																affichageDeboguageFalse))
										.addGap(45, 45, 45)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																m_LabelAfficher)
														.addComponent(
																m_LabelIgnorer))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				m_LabelApparitionAsteroide)
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				m_LabelChangementJoueur))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								m_RadioButtonAparaitionAsteroideIgnore)
																						.addComponent(
																								m_RadioButtonAparaitionAsteroide))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								m_RadioButtonChangementModeVirtuel,
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								m_RadioButtonChangementModeJoueurVirtuelIgnore,
																								javax.swing.GroupLayout.Alignment.TRAILING))))
										.addGap(26, 26, 26)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				m_LabelEclairage)
																		.addGap(8,
																				8,
																				8))
														.addComponent(
																m_RadioButtonActiveEclairage,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_RadioButtonActiveEclairageIgnore,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_LabelIdentificationJoueur)
														.addComponent(
																m_RadioButtonIdentificationCible)
														.addComponent(
																m_RadioButtonIdentificationCibleIgnore))
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(27,
																				27,
																				27)
																		.addComponent(
																				m_LabelIdentificationCadre)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				7,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(25,
																				25,
																				25)
																		.addComponent(
																				m_RadioButtonIdentificationCadreDepart))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel4Layout
																		.createSequentialGroup()
																		.addGap(25,
																				25,
																				25)
																		.addComponent(
																				m_RadioButtonIdentificationCadreDepartIgnore)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																m_RadioButtonIdentificationZonePassageIgnore,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_RadioButtonIdentificationZonePassage,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_LabelIdentificationZonePassage,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																m_LabelIdentificationLimiteAttraction,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_RadioButtenIdentificationLimiteAttraction,
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																m_RadioButtenIdentificationLimiteAttractionIgnore,
																javax.swing.GroupLayout.Alignment.TRAILING))
										.addGap(33, 33, 33)));

		m_TabbedPaneTouche.addTab("Messages de déboguage", jPanel4);

		jButton11.setText("annuler");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});

		jButton12.setText("ok");
		jButton12.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				// Enregistrer la configuration
				SauverConfigurationDebogage();

				// Envoyer au modèle
				FacadeCpp.fctC_obtenirOptionDebogage(affichageDeboguageTrue
						.isSelected(), m_RadioButtonAparaitionAsteroide
						.isSelected(), m_RadioButtonChangementModeVirtuel
						.isSelected(), m_RadioButtonActiveEclairage
						.isSelected(), m_RadioButtonIdentificationCible
						.isSelected(), m_RadioButtonIdentificationCadreDepart
						.isSelected(), m_RadioButtonIdentificationZonePassage
						.isSelected(),
						m_RadioButtenIdentificationLimiteAttraction
								.isSelected());

				int duree;
				switch (m_ComboBoxDureePartie.getSelectedIndex()) {
				case 0:
					duree = 30;
					break;
				case 1:
					duree = 45;
					break;
				case 2:
					duree = 60;
					break;
				case 3:
					duree = 90;
					break;
				case 4:
					duree = 120;
					break;
				case 5:
					duree = 150;
					break;
				case 6:
					duree = 180;
					break;
				case 7:
					duree = 240;
					break;
				case 8:
					duree = 300;
					break;
				default:
					duree = 30;
					break;
				}

				FacadeCpp.fctC_obtenirInfoPartie(duree,
						(Integer) m_SpinnerPtVie.getValue());

				jButton12ActionPerformed(evt);

			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						jPanel2Layout.createSequentialGroup()
								.addContainerGap(298, Short.MAX_VALUE)
								.addComponent(jButton12).addGap(140, 140, 140)
								.addComponent(jButton11).addGap(195, 195, 195))
				.addGroup(
						jPanel2Layout
								.createSequentialGroup()
								.addContainerGap()
								.addComponent(m_TabbedPaneTouche,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										729,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												m_TabbedPaneTouche,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												474, Short.MAX_VALUE)
										.addGap(20, 20, 20)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton11)
														.addComponent(jButton12))
										.addContainerGap()));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addContainerGap()
						.addComponent(jPanel2,
								javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		LireConfigurationDebogage();
		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton4ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton4ActionPerformed

	private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton7ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton7ActionPerformed

	private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton8ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton8ActionPerformed

	private void affichageDeboguageTrueActionPerformed(
			java.awt.event.ActionEvent evt) {// GEN-FIRST:event_affichageDeboguageTrueActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_affichageDeboguageTrueActionPerformed

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
	// TODO add your handling code here:

		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonHautJoueur2),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton1ActionPerformed

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonDemiTourJoueur1),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton2ActionPerformed

	private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
	// TODO add your handling code here:
		char lettre = 65;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonDroiteJoueur1),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton3ActionPerformed

	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre))
			config.changeValue(bouttons.getSetLabel(m_ButtonTirJoueur2), lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton16ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonDemiTourJoueur2),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton16ActionPerformed

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jRadioButton1ActionPerformed
	// TODO add your handling code here:
	}// GEN-LAST:event_jRadioButton1ActionPerformed

	private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton12ActionPerformed
	// TODO add your handling code here:
	// this.saveConfiguration();
		this.fenetrePrincipale.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton12ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
	// TODO add your handling code here:
		this.fenetrePrincipale.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jButton11ActionPerformed

	private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton13ActionPerformed
	// TODO add your handling code here:
		config.reinitialiserJoueur1();
	}// GEN-LAST:event_jButton13ActionPerformed

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton14ActionPerformed
	// TODO add your handling code here:
		config.reinitialiserJoueur2();
	}// GEN-LAST:event_jButton14ActionPerformed

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton15ActionPerformed
	// TODO add your handling code here:
		char lettre = 65;

		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonHautJoueur1),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}

	}// GEN-LAST:event_jButton15ActionPerformed

	private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
	// TODO add your handling code here:
		char lettre = 65;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonGaucheJoueur1),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton4ActionPerformed

	private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonTirJoueur1), lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton5ActionPerformed

	private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton8ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonDroiteJoueur2),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton8ActionPerformed

	private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton9ActionPerformed
	// TODO add your handling code here:
		char lettre = 61;
		if (!config.dejaUtiliser(lettre)
				&& !config.dejaUtiliser(Character.toLowerCase(lettre)))
			config.changeValue(bouttons.getSetLabel(m_ButtonGaucheJoueur2),
					lettre);
		else {
			// custom title, custom icon
			JOptionPane.showMessageDialog(null, "la touche deja assignee.",
					"erreur de saisie", JOptionPane.ERROR_MESSAGE, null);
		}
	}// GEN-LAST:event_jButton9ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	/*
	 * public static void main(String args[]) { try { for
	 * (javax.swing.UIManager.LookAndFeelInfo info :
	 * javax.swing.UIManager.getInstalledLookAndFeels()) { if
	 * ("Nimbus".equals(info.getName())) {
	 * javax.swing.UIManager.setLookAndFeel(info.getClassName()); break; } } }
	 * catch (ClassNotFoundException ex) {
	 * java.util.logging.Logger.getLogger(test1
	 * .class.getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (InstantiationException ex) {
	 * java.util.logging.Logger.getLogger(test1.class
	 * .getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (IllegalAccessException ex) {
	 * java.util.logging.Logger.getLogger(test1.class
	 * .getName()).log(java.util.logging.Level.SEVERE, null, ex); } catch
	 * (javax.swing.UnsupportedLookAndFeelException ex) {
	 * java.util.logging.Logger
	 * .getLogger(test1.class.getName()).log(java.util.logging.Level.SEVERE,
	 * null, ex); } //</editor-fold>
	 * 
	 * java.awt.EventQueue.invokeLater(new Runnable() {
	 * 
	 * public void run() { new test1().setVisible(true);
	 * 
	 * } }); }
	 */

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JRadioButton affichageDeboguageFalse;
	private javax.swing.JRadioButton affichageDeboguageTrue;
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.ButtonGroup buttonGroup2;
	private javax.swing.ButtonGroup buttonGroup3;
	private javax.swing.ButtonGroup buttonGroup4;
	private javax.swing.ButtonGroup buttonGroup5;
	private javax.swing.ButtonGroup buttonGroup6;
	private javax.swing.ButtonGroup buttonGroup7;
	private javax.swing.ButtonGroup buttonGroup8;
	private javax.swing.Box.Filler filler2;
	private javax.swing.JButton m_ButtonHautJoueur2;
	private javax.swing.JButton m_ButtonTirJoueur2;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton m_ButtonValeurDefautJoueur1;
	private javax.swing.JButton m_ButtonValeurDefautJoueur2;
	private javax.swing.JButton m_ButtonHautJoueur1;
	private javax.swing.JButton m_ButtonDemiTourJoueur2;
	private javax.swing.JButton m_ButtonDemiTourJoueur1;
	private javax.swing.JButton m_ButtonDroiteJoueur1;
	private javax.swing.JButton m_ButtonGaucheJoueur1;
	private javax.swing.JButton m_ButtonTirJoueur1;
	private javax.swing.JButton m_ButtonDroiteJoueur2;
	private javax.swing.JButton m_ButtonGaucheJoueur2;
	@SuppressWarnings("rawtypes")
	private javax.swing.JComboBox m_ComboBoxDureePartie;
	private javax.swing.JLabel m_LabelPtVieStations;
	private javax.swing.JLabel m_LabelApparitionAsteroide;
	private javax.swing.JLabel m_LabelChangementJoueur;
	private javax.swing.JLabel m_LabelEclairage;
	private javax.swing.JLabel m_LabelIdentificationJoueur;
	private javax.swing.JLabel m_LabelIdentificationCadre;
	private javax.swing.JLabel m_LabelIdentificationZonePassage;
	private javax.swing.JLabel m_LabelIdentificationLimiteAttraction;
	private javax.swing.JLabel m_LabelJoueur1;
	private javax.swing.JLabel m_LabelIgnorer;
	private javax.swing.JLabel m_LabelAfficher;
	private javax.swing.JLabel m_LabelAfficahgeDebogage;
	private javax.swing.JLabel m_LabelAvancer;
	private javax.swing.JLabel m_LabelDemiTour;
	private javax.swing.JLabel m_LabelTournerDroite;
	private javax.swing.JLabel m_LabelTournerGauche;
	private javax.swing.JLabel m_LabelTir;
	private javax.swing.JLabel m_LabelJoueur2;
	private javax.swing.JLabel m_LabelDureePartie;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JRadioButton m_RadioButtonAparaitionAsteroide;
	private javax.swing.JRadioButton m_RadioButtonIdentificationCadreDepartIgnore;
	private javax.swing.JRadioButton m_RadioButtonIdentificationZonePassage;
	private javax.swing.JRadioButton m_RadioButtonIdentificationZonePassageIgnore;
	private javax.swing.JRadioButton m_RadioButtenIdentificationLimiteAttraction;
	private javax.swing.JRadioButton m_RadioButtenIdentificationLimiteAttractionIgnore;
	private javax.swing.JRadioButton m_RadioButtonAparaitionAsteroideIgnore;
	private javax.swing.JRadioButton m_RadioButtonChangementModeVirtuel;
	private javax.swing.JRadioButton m_RadioButtonChangementModeJoueurVirtuelIgnore;
	private javax.swing.JRadioButton m_RadioButtonActiveEclairageIgnore;
	private javax.swing.JRadioButton m_RadioButtonActiveEclairage;
	private javax.swing.JRadioButton m_RadioButtonIdentificationCibleIgnore;
	private javax.swing.JRadioButton m_RadioButtonIdentificationCible;
	private javax.swing.JRadioButton m_RadioButtonIdentificationCadreDepart;
	private javax.swing.JSpinner m_SpinnerPtVie;
	private javax.swing.JTabbedPane m_TabbedPaneTouche;
	// End of variables declaration//GEN-END:variables
}
